- README.md
added slack badge a a link to join it
> 📰 updated readme

- September Challenge 2020 Division 2/TREE2.cpp
TREE2
https://www.codechef.com/SEPT20B/problems/TREE2
Example Input
1
3
1 2 3
Example Output
3
---
> 📰 added TREE2.cpp

- Practice/WATMELON .cpp
> Create WATMELON .cpp

- Practice/CYCLICQD .cpp
- Practice/OLYRANK.cpp
> Added More Updates

- Practice/ADJHATE .cpp
> Create ADJHATE .cpp

- Practice/kadanes.cpp
> added_kadanesalgo

- Practice/nextpermutation.cpp
> added next permuation

- Practice/patternbasics.cpp
> added pattern based ques

- LeetCode/Strings/strings.cpp
> Added Leetcode problem on string

- Love Babbar DSA Sheet/18.cpp
- Love Babbar DSA Sheet/6.cpp
**To test:** 
Given an array (or string), the task is to reverse the array/string.
Examples : 
- For Reverse of a string: 
Input  : arr[] = {1, 2, 3}
Output : arr[] = {3, 2, 1}
Input :  arr[] = {4, 5, 1, 2}
Output : arr[] = {2, 1, 5, 4}
- For Kadane's algo:
Input:
N = 5
Arr[] = {1,2,3,-2,5}
Output:
9
Explanation:
Max subarray sum is 9
of elements (1, 2, 3, -2, 5) which 
is a contiguous subarray.
---
> :green_circle: Reverse of a string

- Love Babbar DSA Sheet/56.cpp
**To test:** 
Example 1:
Input: s = ["h","e","l","l","o"]
Output: ["o","l","l","e","h"]
Example 2:
Input: s = ["H","a","n","n","a","h"]
Output: ["h","a","n","n","a","H"]
---
> :green_circle: Reverse of characters in string

- LeetCode/Strings/string_compression.cpp
> added leetcode string compression in c++

- RGB_switches.ino
> RGB switches

- Mumbai.ino
- motor_testing.ino
> motor_testing

- Accelerometer.ino
> glove_test_1

- LeetCode/Leetcode Problems/[51] N-Queens.cpp
> add : N Queens Creative way

- LeetCode/Leetcode Problems/[52] N-Queens-2.cpp
> Create [52] N-Queens-2.cpp

- LeetCode/Leetcode Problems/[1835] Find XOR Sum of All Pairs Bitwise AND.cpp
> Create [1835] Find XOR Sum of All Pairs Bitwise AND.cpp

- LeetCode/Leetcode Problems/best_time_to_buy.cpp
- LeetCode/Leetcode Problems/next_permutation.cpp
- LeetCode/Strings/.cph/.strings.cpp_1700eafee230eff19101ebd453b348da.prob
- Love Babbar DSA Sheet/.~lock.FINAL450.xlsx#
> 121. Best Time to Buy Solution

- LeetCode/Leetcode Problems/rotate_matrix.cpp
> 48. Rotate Image Solution

- LeetCode/Leetcode Problems/alternate_swap.cpp
> Alternate Swap Solution
